# Generated by Django 3.1.14 on 2022-10-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
    ]
